# Generated by Django 4.1.1 on 2022-11-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='salt',
            field=models.CharField(default='', max_length=15),
        ),
    ]
