# Generated by Django 4.1.2 on 2022-11-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="branchID",
            field=models.IntegerField(default=1, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="typeID",
            field=models.IntegerField(default=1, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="branchID",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rental",
            name="branchID",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rental",
            name="carID",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rental",
            name="typeID",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
